---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stefan.
--- DateTime: 20.05.2019 21:51
---
require("ts3init")                    -- Required for ts3RegisterModule
require("muteclient/main")

local MODULE_NAME = "muteclient"


-- Register the callback function
ts3RegisterModule(MODULE_NAME, registeredEvents)
